### ISSUE TITLE
Component ID

### ISSUE THREAD

**Issue by Spucelik** [bschlintz/spfx-external-sharing-banner#2]
The Tenant Wide Extensions list requires a valid Component ID.  I took the one from the manifest, which matches the product ID (004B6D5E-AEE8-499B-9FE8-06757CFD043B) but I was not able to save the items in the Tenant Wide Extensions list.  It finally took 1e2688c4-99d8-4897-8871-a9c151ccfc87 but the banner doesn't show up.

Please verify this is correct.

**Comment by bschlintz** [comment]
The component ID for the extension can be found in the file below.

https://github.com/bschlintz/spfx-external-sharing-banner/blob/9acb5305f1851fd0b9788f1da24274cc2e7b006b/sharepoint/assets/ClientSideInstance.xml#L6
